apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: LoadBalancer  # Définit le type comme NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana  # Assure-toi que ce sélecteur correspond à ton déploiement Grafana
