replicaCount: 1

image:
  repository: prom/prometheus
  tag: v2.22.0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9090

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"
