apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  type: LoadBalancer  # Définit le type comme NodePort
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
