replicaCount: 1

image:
  repository: grafana/grafana
  tag: 7.3.5
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

adminPassword: admin

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"
