apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubecast-detector.fullname" . }}-role
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]