apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubecast-detector.fullname" . }}
  labels:
    {{- include "kubecast-detector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    {{- include "kubecast-detector.selectorLabels" . | nindent 4 }}
